services:
    suricata:
        build: .
        deploy:
          resources:
            limits:
              cpus: '1'
              memory: 2G
        container_name: suricata
        stdin_open: true
        tty: true
        network_mode: host
        cap_add:
            - net_admin
            - net_raw
            - sys_nice
            - sys_time  # Adicionado para permitir a alteração da hora
        volumes:
            - ./logs:/var/log/suricata
            - ./suricata.yaml:/etc/suricata/suricata.yaml
            - ./rules:/var/lib/suricata/rules
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        entrypoint: ["usr/local/bin/entrypoint.sh"]
